### PR TITLE
Fix PSR-0 PEAR_Error autoload for phpstan

### PR DESCRIPTION
**Pull request by mvorisek**
9 years ago the autoload was fixed by https://github.com/pear/pear-core-minimal/commit/f1864ea12bdf70b32b6779e8751cebe9f85d70d1, the fix is not bad, but phpstan does not follow includes.

Newly it is fixed to mimic the autoload in the upstream https://github.com/pear/pear-core/blob/v1.10.14/composer.json#L50 which is compatible /w phpstan /wo having to use the include/fix above.

The proposed PR is compatible with https://github.com/pear/pear-core-minimal/blob/v1.10.14/copy-from-pear-core.sh updating script.

### CODE REVIEW

**Comment by mvorisek** [comment]
Hi @ashnazg, may I ask you to merge this PR?

**Comment by ashnazg** [comment]
@mvorisek , I'd propose a different approach:
* in `pear-core`, pull the `PEAR_Error` class out of the `PEAR.php` file and into its own new `PEAR/Error.php` class file
* in the `PEAR.php` file, keep some `!class_exists()` logic for the `PEAR_Error` class that can then `require` the `PEAR/Error.php` at runtime when needed
* add `PEAR/Error.php` to the copy script that keeps `pear-core-minimal` in sync

If this approach doesn't present any problems from your perspective, I'll look into making it happen.

**Comment by mvorisek** [comment]
I see this PR as unification that should be merged, as in the core/upstream repo there is already `classmap` autoload, so in this repo should be the same autoload too. So I propose to merge this PR and then possibly investigate a possible refactoring.

**Comment by ashnazg** [comment]
Ah, I see your point about `pear-core` also already doing `classmap`...

**Review by ashnazg — APPROVED** [review]

**Comment by mvorisek** [comment]
@ashnazg can a new release be tagged please?

**Comment by ashnazg** [comment]
v.10.15 is released

**Comment by alecpl** [comment]
This new release does not include this change.

See: https://github.com/pear/pear-core-minimal/commits/v1.10.15/ vs. https://github.com/pear/pear-core-minimal/commits/master/

We'll need a new release.

**Comment by ashnazg** [comment]
I've redone the v1.10.15 release... see if that fixed it for you.

**Comment by mvorisek** [comment]
LGTM 👍

**Pull request merged**
